# Generated by Django 3.2 on 2021-04-30 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FootballClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre del club')),
                ('foundation_year', models.CharField(max_length=50, verbose_name='Año de fundación')),
                ('owner', models.CharField(max_length=50, verbose_name='Dueño')),
                ('city', models.CharField(max_length=50, verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Club de futbol',
                'verbose_name_plural': 'Clubs de futbol',
                'db_table': 'futbolclub',
            },
        ),
    ]
