# Generated by Django 3.2 on 2021-04-30 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballclub',
            name='foundation_year',
            field=models.PositiveIntegerField(verbose_name='Año de fundación'),
        ),
    ]
